name: run-workflow-C

on:
  schedule:
  # Runs at 01:00 UTC every day.
    - cron:  '0 1 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-workflow-C:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Create env file
      run: |
        touch .env
        echo DRIVER = '${{ secrets.DRIVER }}' >> .env
        echo SERVER = '${{ secrets.SERVER }}' >> .env
        echo DATABASE = '${{ secrets.DATABASE }}' >> .env
        echo UID = '${{ secrets.UID }}' >> .env
        echo PASSWORD = '${{ secrets.PASSWORD }}' >> .env
        echo C1_QUERY1 = '${{ secrets.C1_QUERY1 }}' >> .env

    - name: Run workflow C
      run: |        
        python main_C.py

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Run workflow C
        branch: ${{ github.head_ref }}
        commit_user_name: JakeBGitHub
        commit_user_email: jake.barrett@ntlworld.com
        commit_author: Jake Barrett <jake.barrett@ntlworld.com>
